name: Typechecking

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  typechecking:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: 3.x
    - name: mypy (pinned)
      run: |
        pip install --upgrade pip
        pip install -U mypy==1.3.0
        pip install -U pydantic
        pip install -U types-setuptools
        mypy blocklib --ignore-missing-imports --no-implicit-optional --disallow-untyped-calls
    - name: mypy (latest)
      run: |
        pip install --upgrade pip
        pip install -U mypy
        pip install -U pydantic
        pip install -U types-setuptools
        mypy blocklib --ignore-missing-imports --no-implicit-optional --disallow-untyped-calls
